=== Sabale-1234/-College-Practical-Assignment/Wt ass 3/Student.dtd
<!ELEMENT Students[
<!ELEMENT Student> (Name,Department,Year,Credit)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Department (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Credit (#PCDATA)>
]>

=== Sabale-1234/-College-Practical-Assignment/Wt ass 3/index.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet href="style.css"?> 
<!DOCTYPE Students SYSTEM "Student.dtd">
<Students>
  <heading>Student Data </heading>
  <Student category="top">
    <Name id="1">Name:Mansi Raut</Name>
    <Department>Department:Computer</Department>
    <Year>Year:Second</Year>
    <Credit>Credit:8.12</Credit>
  </Student>
  <Student category="top">
    <Name id="1">Name:Jay Jadhav</Name>
    <Department>Department:Information Technology</Department>
    <Year>Year:Second</Year>
    <Credit>Credit:9.16</Credit>
  </Student>
  <Student category="top">
    <Name id="1">Name:Pranoti Bhartakke</Name>
    <Department>Department:Mechanical</Department>
    <Year>Year:Third</Year>
    <Credit>Credit:8.6</Credit>
  </Student>
  <Student category="top">
    <Name id="1">Name: Prajakta Surve </Name>
    <Department>Department:Civil</Department>
    <Year>Year:fourth</Year>
    <Credit>Credit:8.88</Credit>
    
  </Student>
</Students>
